#!/usr/bin/env bash

# paths
SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$SCRIPTS_DIR/.."

# exit on error
# echo on
set -e
set -x

cd "$ROOT_DIR"
pip install --upgrade pip
pip install -e .[dev]
