#!/usr/bin/env bash
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
set -e


cd "$ROOT_DIR"


# install dev
pip install --upgrade  pip setuptools
pip install --editable .[dev]
