#!/usr/bin/env bash
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
set -e


cd "$ROOT_DIR"


# update action
function update() {
  NAME=$1
  pyside6-uic "qtcreator/$NAME.ui" > "qtrf/widgets/$NAME/ui_$NAME.py"
}


# update each ui object
update file
