#!/usr/bin/env bash


# paths
SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$SCRIPTS_DIR/.."

# version
VERSION="$1"

# exit on error
# echo on
set -e
set -x

cd "$ROOT_DIR"
pip install twine
twine upload "dist/qtrf-$VERSION.tar.gz"
twine upload "dist/qtrf-$VERSION-py2.py3-none-any.whl"
